---
# Docker User
dockerUser: geoffh1977
dockerUserEmail: geoffh1977@gmail.com
license: gnu-gpl-v3.0

# Source Build Variables
buildImageName: alpine
buildImageVersion: 3

# Final Image Variables
finalImageName: evernote-monitor
finalImageVersion: latest
appName: Evernote Monitor
